# Generated by Django 4.2.20 on 2025-04-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='name',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rmaoffice',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='rmaoffice',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rmaoffice',
            name='last_updated',
        ),
        migrations.CreateModel(
            name='LossExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_experience_rate', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial_data.populationarea')),
            ],
        ),
    ]
