# Generated by Django 4.2.20 on 2025-04-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0002_manager_remove_bank_bank_id_remove_bank_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmaoffice',
            name='code_tel',
        ),
        migrations.RemoveField(
            model_name='rmaoffice',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='rmaoffice',
            name='tel_GSM',
        ),
    ]
