# Generated by Django 4.2.20 on 2025-04-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0003_remove_rmaoffice_code_tel_remove_rmaoffice_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmabgd',
            name='type_BGD',
            field=models.CharField(choices=[('BGD CLASSIQUE', 'classique'), ('BGD NOUVEAU_MODELE', 'nouveau_modele'), ('BGD TREMPLEIN', 'tremplein'), ('BGD PARTENAIRE', 'partenaire'), ('SNTL', 'SNTL')], max_length=50),
        ),
    ]
