# Generated by Django 4.2.20 on 2025-04-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0004_alter_rmabgd_type_bgd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rmabgd',
            options={'verbose_name': 'RMA BGD', 'verbose_name_plural': 'RMA BGDs'},
        ),
        migrations.AlterField(
            model_name='rmabgd',
            name='Partenaire',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rmabgd',
            name='RMA_BGD_state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rmabgd',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rmabgd',
            name='type_BGD',
            field=models.CharField(max_length=100),
        ),
    ]
