# Generated by Django 4.2.20 on 2025-05-19 10:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0005_alter_rmabgd_options_alter_rmabgd_partenaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('total_population', models.IntegerField()),
                ('estimated_vehicles', models.IntegerField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='coveragescore',
            name='bank_partnership_factor',
        ),
        migrations.RemoveField(
            model_name='coveragescore',
            name='competitor_factor',
        ),
        migrations.RemoveField(
            model_name='coveragescore',
            name='coverage_percentage',
        ),
        migrations.RemoveField(
            model_name='coveragescore',
            name='nearest_office',
        ),
        migrations.RemoveField(
            model_name='coveragescore',
            name='population_covered',
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spatial_data.area')),
                ('population_2004', models.IntegerField(default=0)),
            ],
            bases=('spatial_data.area',),
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('area_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spatial_data.area')),
            ],
            bases=('spatial_data.area',),
        ),
        migrations.AlterField(
            model_name='coveragescore',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_scores', to='spatial_data.area'),
        ),
        migrations.AlterField(
            model_name='lossexperience',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial_data.area'),
        ),
        migrations.DeleteModel(
            name='PopulationArea',
        ),
    ]
