# Generated by Django 4.2.20 on 2025-05-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0006_area_remove_coveragescore_bank_partnership_factor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='total_population',
            new_name='population',
        ),
    ]
