# Generated by Django 4.2.20 on 2025-05-19 11:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0008_alter_area_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
