# Generated by Django 4.2.20 on 2025-05-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0009_alter_area_boundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='population_2004',
        ),
    ]
