# Generated by Django 4.2.21 on 2025-05-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0010_remove_commune_population_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_ratio', models.FloatField(default=0)),
                ('RMA_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial_data.rmaoffice')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial_data.commune')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial_data.province')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='insured_population',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='area',
            name='estimated_vehicles',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.DeleteModel(
            name='LossExperience',
        ),
    ]
