# Generated by Django 4.2.21 on 2025-05-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0011_lossratio_area_insured_population_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='bank_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='area',
            name='competition_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='coveragescore',
            name='potential',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', help_text='Potential for coverage improvement', max_length=50),
        ),
    ]
