# Generated by Django 4.2.21 on 2025-05-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0012_area_bank_count_area_competition_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_date', models.DateTimeField(auto_now=True)),
                ('raw_min', models.FloatField()),
                ('raw_max', models.FloatField()),
                ('raw_mean', models.FloatField()),
                ('raw_stddev', models.FloatField()),
            ],
        ),
    ]
