# Generated by Django 4.2.21 on 2025-05-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0013_coveragestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragestats',
            name='bank_mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='bank_std',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='comp_mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='comp_std',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='gap_mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='gap_std',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='pop_mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='pop_std',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='veh_mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='veh_std',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coveragestats',
            name='calc_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coveragestats',
            name='raw_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coveragestats',
            name='raw_mean',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coveragestats',
            name='raw_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coveragestats',
            name='raw_stddev',
            field=models.FloatField(default=0.0),
        ),
    ]
