# Generated by Django 4.2.21 on 2025-05-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0014_coveragestats_bank_mean_coveragestats_bank_std_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragestats',
            name='access_mean',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='access_stddev',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
