# Generated by Django 4.2.21 on 2025-05-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0015_coveragestats_access_mean_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coveragestats',
            old_name='access_stddev',
            new_name='access_std',
        ),
    ]
