# Generated by Django 4.2.21 on 2025-05-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0016_rename_access_stddev_coveragestats_access_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragestats',
            name='access_mean',
        ),
        migrations.RemoveField(
            model_name='coveragestats',
            name='access_std',
        ),
        migrations.RemoveField(
            model_name='coveragestats',
            name='raw_max',
        ),
        migrations.RemoveField(
            model_name='coveragestats',
            name='raw_mean',
        ),
        migrations.RemoveField(
            model_name='coveragestats',
            name='raw_min',
        ),
        migrations.RemoveField(
            model_name='coveragestats',
            name='raw_stddev',
        ),
        migrations.AddField(
            model_name='area',
            name='bank_intensity',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='area',
            name='competition_intensity',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
