# Generated by Django 4.2.21 on 2025-06-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0017_remove_coveragestats_access_mean_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='company_name',
            new_name='agency_name',
        ),
    ]
