# Generated by Django 4.2.21 on 2025-06-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0019_alter_commune_options_alter_coveragescore_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragescore',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial_data.area'),
        ),
    ]
