# Generated by Django 4.2.21 on 2025-06-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0020_alter_coveragescore_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.FloatField(help_text='Value of the variable')),
                ('description', models.TextField(blank=True, help_text='Description of what this variable is used for', null=True)),
            ],
        ),
    ]
