# Generated by Django 4.2.21 on 2025-06-04 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0021_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='estimated_vehicles',
            field=models.IntegerField(default=0, help_text='Estimated number of vehicles'),
        ),
        migrations.AlterField(
            model_name='area',
            name='insured_population',
            field=models.IntegerField(default=0, help_text='Estimated insured population'),
        ),
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('CA_values', models.FloatField(default=0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial_data.rmaoffice')),
            ],
        ),
    ]
