# Generated by Django 4.2.21 on 2025-06-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0022_alter_area_estimated_vehicles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ca',
            old_name='CA_values',
            new_name='CA_value',
        ),
    ]
