# Generated by Django 4.2.21 on 2025-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0023_rename_ca_values_ca_ca_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragescore',
            name='rma_office_performance_score',
            field=models.FloatField(blank=True, help_text='Component score from nearby RMA office performance (0-100)', null=True),
        ),
    ]
