# Generated by Django 4.2.21 on 2025-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0024_coveragescore_rma_office_performance_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragestats',
            name='rma_office_influence_mean',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='coveragestats',
            name='rma_office_influence_std',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
