# Generated by Django 4.2.21 on 2025-06-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0025_coveragestats_rma_office_influence_mean_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('provinces', models.ManyToManyField(blank=True, help_text='Provinces within this region', related_name='regions', to='spatial_data.province')),
            ],
        ),
    ]
