# Generated by Django 4.2.21 on 2025-06-04 18:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_data', '0026_regionadministrative'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMDiscoveredCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(help_text='OpenStreetMap ID of the element')),
                ('osm_type', models.CharField(help_text="OSM element type: 'node', 'way', or 'relation'", max_length=10)),
                ('name_from_osm', models.CharField(blank=True, help_text='Name as found on OSM', max_length=255, null=True)),
                ('address_from_osm', models.TextField(blank=True, help_text='Address as found on OSM', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('osm_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geometric location from OSM', null=True, srid=4326)),
                ('tags_from_osm', models.JSONField(default=dict, help_text='Raw OSM tags associated with the place')),
                ('first_seen_globally', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_globally', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OSM Discovered Competitor',
                'verbose_name_plural': 'OSM Discovered Competitors',
                'unique_together': {('osm_id', 'osm_type')},
            },
        ),
        migrations.CreateModel(
            name='AgencyOSMCompetitorProximity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_near_office', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_near_office', models.DateTimeField(auto_now=True)),
                ('osm_competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial_data.osmdiscoveredcompetitor')),
                ('rma_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial_data.rmaoffice')),
            ],
            options={
                'verbose_name': 'RMA Office - OSM Competitor Proximity',
                'verbose_name_plural': 'RMA Office - OSM Competitor Proximities',
                'unique_together': {('rma_office', 'osm_competitor')},
            },
        ),
    ]
